In [1]:
import numpy as np


In [2]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [4]:
#get the frist attribute of array
x[0,]

1

In [5]:
x[5,]

6

In [6]:
x[:4]

array([1, 2, 3, 4])

In [7]:
#save file in default directori
np.save('x',x)

In [8]:
# access file
np.load('x.npy')

array([1, 2, 3, 4, 5, 6])